server:
  port: 9000

kafka:
  bootstrapAddress: localhost:9092

topic:
  message:
    name: hyomee
  modelVo:
    name: modelvo
  filtered:
    name : filtered
  partitioned:
    name: partitioned


consumerGroup:
  hyomeeGrp: hyomee
  headerGrp: headers
  partitionsGrp: partitions
  filterGrp: filter
  modelVoGrp: greeting

filter: hi

logging:
  level:
    root: ERROR ##
    org.springframework: ERROR
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.hyomee : DEBUG

